# Generated by Django 4.2.7 on 2023-11-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('director', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
                ('judge', models.FloatField()),
                ('inq', models.CharField(max_length=64)),
            ],
        ),
    ]
